language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "node"
  - "iojs"
services:
  - redis-server
script:
  - npm start 8080 &
  - curl -X POST "http://localhost:8080/create?alias=test&url=hello"
  - curl -v "http://localhost:8080/test"
