language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "node"
  - "iojs"
services:
  - redis-server
before_script:
  - echo "{\"port\":8080,\"redis\":6379}" > config.json
script:
  - npm start & sleep 30
